/* Generated By:JavaCC: Do not edit this line. SiteswapParserConstants.java */
package jugglinglab.notation;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SiteswapParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 4;
  /** RegularExpression Id. */
  int LET = 5;
  /** RegularExpression Id. */
  int MOD = 6;
  /** RegularExpression Id. */
  int SPC = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NUM>",
    "<LET>",
    "<MOD>",
    "<SPC>",
    "\"*\"",
    "\"(\"",
    "\"^\"",
    "\")\"",
    "\"!\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"p\"",
    "\"x\"",
    "\"/\"",
    "\"R\"",
    "\"L\"",
    "\"<\"",
    "\"|\"",
    "\">\"",
    "\"?\"",
  };

}
