/* SiteswapParser.java */ /* Generated By:JavaCC: Do not edit this line. SiteswapParser.java */
@file:Suppress("SENSELESS_COMPARISON", "unused", "UnusedVariable", "SameParameterValue")

package jugglinglab.notation.ssparser

//
// This file is part of Juggling Lab.  It was automatically generated by JavaCC
// from the grammar file "SiteswapParser.jj".
//
// DO NOT EDIT THIS FILE DIRECTLY, AS YOUR CHANGES WILL LIKELY BE OVERWRITTEN
//

class SiteswapParser : SiteswapParserConstants {
    @Throws(ParseException::class)
    fun MakeTree(): SiteswapTreeItem {
        val b: SiteswapTreeItem
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            SiteswapParserConstants.SPC -> {
                jj_consume_token(SiteswapParserConstants.SPC)
            }

            else -> {
                jj_la1[0] = jj_gen
            }
        }
        b = Pattern()
        jj_consume_token(0)
        run { if ("" != null) return b }
        throw Error("Missing return statement in function")
    }

    @Throws(ParseException::class)
    fun Pattern(): SiteswapTreeItem {
        val b: SiteswapTreeItem
        var c: SiteswapTreeItem
        var n: Int
        b = SiteswapTreeItem(SiteswapTreeItem.TYPE_PATTERN)
        label_1@ while (true) {
            if (jj_2_1(2147483647)) {
                c = GroupedPattern()
            } else {
                when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                    SiteswapParserConstants.NUM, SiteswapParserConstants.LET, 9, 14, 16, 17, 18, 21, 22 -> {
                        c = SoloSequence()
                    }

                    23 -> {
                        c = PassingSequence()
                    }

                    26 -> {
                        n = Wildcard()
                        c = SiteswapTreeItem(SiteswapTreeItem.TYPE_WILDCARD)
                        c.beats = n
                    }

                    else -> {
                        jj_la1[1] = jj_gen
                        jj_consume_token(-1)
                        throw ParseException()
                    }
                }
            }
            b.addChild(c)
            when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                SiteswapParserConstants.NUM, SiteswapParserConstants.LET, 9, 14, 16, 17, 18, 21, 22, 23, 26 -> {
                }

                else -> {
                    jj_la1[2] = jj_gen
                    break@label_1
                }
            }
        }
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            8 -> {
                jj_consume_token(8)
                b.switchrepeat = true
            }

            else -> {
                jj_la1[3] = jj_gen
            }
        }
        b.jugglers = jugglers
        run { if ("" != null) return b }
        throw Error("Missing return statement in function")
    }

    @Throws(ParseException::class)
    fun GroupedPattern(): SiteswapTreeItem {
        val b: SiteswapTreeItem
        val c: SiteswapTreeItem
        val n: Int
        b = SiteswapTreeItem(SiteswapTreeItem.TYPE_GROUPED_PATTERN)
        jj_consume_token(9)
        c = Pattern()
        b.addChild(c)
        b.repeats = 1
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            10 -> {
                jj_consume_token(10)
                n = Number()
                b.repeats = n
            }

            else -> {
                jj_la1[4] = jj_gen
            }
        }
        jj_consume_token(11)
        run { if ("" != null) return b }
        throw Error("Missing return statement in function")
    }

    @Suppress("ControlFlowWithEmptyBody")
    @Throws(ParseException::class)
    fun SoloSequence(): SiteswapTreeItem {
        val b: SiteswapTreeItem
        var c: SiteswapTreeItem
        val s: Token? = null
        b = SiteswapTreeItem(SiteswapTreeItem.TYPE_SOLO_SEQUENCE)
        current_juggler = 1
        current_beat = 0
        label_2@ while (true) {
            when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                SiteswapParserConstants.NUM, SiteswapParserConstants.LET, 14, 16, 17, 18 -> {
                    c = SoloMultiThrow()
                    current_beat++
                    b.addChild(c)
                }

                9 -> {
                    c = SoloPairedThrow()
                    current_beat += 2
                    when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                        12 -> {
                            jj_consume_token(12)
                            current_beat--
                        }

                        else -> {
                            jj_la1[5] = jj_gen
                        }
                    }
                    b.addChild(c)
                    when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                        SiteswapParserConstants.SPC -> {
                            jj_consume_token(SiteswapParserConstants.SPC)
                        }

                        else -> {
                            jj_la1[6] = jj_gen
                        }
                    }
                }

                21, 22 -> {
                    c = SoloHandSpecifier()
                    when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                        SiteswapParserConstants.SPC -> {
                            jj_consume_token(SiteswapParserConstants.SPC)
                        }

                        else -> {
                            jj_la1[7] = jj_gen
                        }
                    }
                    b.addChild(c)
                }

                else -> {
                    jj_la1[8] = jj_gen
                    jj_consume_token(-1)
                    throw ParseException()
                }
            }
            if (jj_2_2(2147483647)) {
            } else {
                break@label_2
            }
        }
        if (jugglers == -1) {
            jugglers = 1
        } else if (jugglers != 1) {
            run { if (true) throw ParseException("Inconsistent number of jugglers") }
        }
        b.source_juggler = 1
        b.beats = current_beat
        run { if ("" != null) return b }
        throw Error("Missing return statement in function")
    }

    @Throws(ParseException::class)
    fun SoloPairedThrow(): SiteswapTreeItem {
        val b: SiteswapTreeItem
        var c: SiteswapTreeItem
        b = SiteswapTreeItem(SiteswapTreeItem.TYPE_SOLO_PAIRED_THROW)
        jj_consume_token(9)
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            SiteswapParserConstants.SPC -> {
                jj_consume_token(SiteswapParserConstants.SPC)
            }

            else -> {
                jj_la1[9] = jj_gen
            }
        }
        c = SoloMultiThrow()
        b.addChild(c)
        jj_consume_token(13)
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            SiteswapParserConstants.SPC -> {
                jj_consume_token(SiteswapParserConstants.SPC)
            }

            else -> {
                jj_la1[10] = jj_gen
            }
        }
        c = SoloMultiThrow()
        b.addChild(c)
        jj_consume_token(11)
        b.source_juggler = 1
        b.seq_beatnum = current_beat
        run { if ("" != null) return b }
        throw Error("Missing return statement in function")
    }

    @Throws(ParseException::class)
    fun SoloMultiThrow(): SiteswapTreeItem {
        val b: SiteswapTreeItem
        var c: SiteswapTreeItem
        b = SiteswapTreeItem(SiteswapTreeItem.TYPE_SOLO_MULTI_THROW)
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            SiteswapParserConstants.NUM, SiteswapParserConstants.LET, 16, 17, 18 -> {
                c = SoloSingleThrow()
                b.addChild(c)
                when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                    SiteswapParserConstants.SPC -> {
                        jj_consume_token(SiteswapParserConstants.SPC)
                    }

                    else -> {
                        jj_la1[11] = jj_gen
                    }
                }
            }

            14 -> {
                jj_consume_token(14)
                when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                    SiteswapParserConstants.SPC -> {
                        jj_consume_token(SiteswapParserConstants.SPC)
                    }

                    else -> {
                        jj_la1[12] = jj_gen
                    }
                }
                label_3@ while (true) {
                    c = SoloSingleThrow()
                    b.addChild(c)
                    when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                        SiteswapParserConstants.SPC -> {
                            jj_consume_token(SiteswapParserConstants.SPC)
                        }

                        else -> {
                            jj_la1[13] = jj_gen
                        }
                    }
                    when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                        SiteswapParserConstants.NUM, SiteswapParserConstants.LET, 16, 17, 18 -> {
                        }

                        else -> {
                            jj_la1[14] = jj_gen
                            break@label_3
                        }
                    }
                }
                jj_consume_token(15)
                when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                    SiteswapParserConstants.SPC -> {
                        jj_consume_token(SiteswapParserConstants.SPC)
                    }

                    else -> {
                        jj_la1[15] = jj_gen
                    }
                }
            }

            else -> {
                jj_la1[16] = jj_gen
                jj_consume_token(-1)
                throw ParseException()
            }
        }
        b.source_juggler = 1
        b.seq_beatnum = current_beat
        run { if ("" != null) return b }
        throw Error("Missing return statement in function")
    }

    @Throws(ParseException::class)
    fun SoloSingleThrow(): SiteswapTreeItem {
        val b: SiteswapTreeItem
        val t: Token
        val mod: String?
        val n: Int
        b = SiteswapTreeItem(SiteswapTreeItem.TYPE_SOLO_SINGLE_THROW)
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            SiteswapParserConstants.NUM -> {
                t = jj_consume_token(SiteswapParserConstants.NUM)
                b.value = (t.image?.toCharArray())?.get(0)?.digitToIntOrNull(36) ?: -1
            }

            SiteswapParserConstants.LET -> {
                t = jj_consume_token(SiteswapParserConstants.LET)
                b.value = (t.image?.toCharArray())?.get(0)?.digitToIntOrNull(36) ?: -1
            }

            16 -> {
                jj_consume_token(16)
                b.value = 25
            }

            17 -> {
                jj_consume_token(17)
                b.value = 33
            }

            18 -> {
                jj_consume_token(18)
                when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                    SiteswapParserConstants.SPC -> {
                        jj_consume_token(SiteswapParserConstants.SPC)
                    }

                    else -> {
                        jj_la1[17] = jj_gen
                    }
                }
                n = Number()
                b.value = n
                when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                    SiteswapParserConstants.SPC -> {
                        jj_consume_token(SiteswapParserConstants.SPC)
                    }

                    else -> {
                        jj_la1[18] = jj_gen
                    }
                }
                jj_consume_token(19)
            }

            else -> {
                jj_la1[19] = jj_gen
                jj_consume_token(-1)
                throw ParseException()
            }
        }
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            17 -> {
                jj_consume_token(17)
                b.x = true
            }

            else -> {
                jj_la1[20] = jj_gen
            }
        }
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            SiteswapParserConstants.MOD -> {
                mod = Modifier()
                b.mod = mod
            }

            else -> {
                jj_la1[21] = jj_gen
            }
        }
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            20 -> {
                jj_consume_token(20)
            }

            else -> {
                jj_la1[22] = jj_gen
            }
        }
        b.source_juggler = 1
        b.dest_juggler = 1
        b.seq_beatnum = current_beat
        run { if ("" != null) return b }
        throw Error("Missing return statement in function")
    }

    @Throws(ParseException::class)
    fun SoloHandSpecifier(): SiteswapTreeItem {
        val b: SiteswapTreeItem
        b = SiteswapTreeItem(SiteswapTreeItem.TYPE_HAND_SPEC)
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            21 -> {
                jj_consume_token(21)
                b.spec_left = false
            }

            22 -> {
                jj_consume_token(22)
                b.spec_left = true
            }

            else -> {
                jj_la1[23] = jj_gen
                jj_consume_token(-1)
                throw ParseException()
            }
        }
        b.source_juggler = 1
        b.seq_beatnum = current_beat
        run { if ("" != null) return b }
        throw Error("Missing return statement in function")
    }

    @Throws(ParseException::class)
    fun PassingSequence(): SiteswapTreeItem {
        val b: SiteswapTreeItem
        var c: SiteswapTreeItem
        b = SiteswapTreeItem(SiteswapTreeItem.TYPE_PASSING_SEQUENCE)
        current_beat = 0
        label_4@ while (true) {
            c = PassingGroup()
            b.jugglers = c.jugglers
            b.addChild(c)
            when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                23 -> {
                }

                else -> {
                    jj_la1[24] = jj_gen
                    break@label_4
                }
            }
        }
        b.beats = current_beat
        run { if ("" != null) return b }
        throw Error("Missing return statement in function")
    }

    @Throws(ParseException::class)
    fun PassingGroup(): SiteswapTreeItem {
        val b: SiteswapTreeItem
        var c: SiteswapTreeItem
        b = SiteswapTreeItem(SiteswapTreeItem.TYPE_PASSING_GROUP)
        current_juggler = 1
        jj_consume_token(23)
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            SiteswapParserConstants.SPC -> {
                jj_consume_token(SiteswapParserConstants.SPC)
            }

            else -> {
                jj_la1[25] = jj_gen
            }
        }
        c = PassingThrows()
        b.beats = c.beats
        b.addChild(c)
        current_juggler++
        label_5@ while (true) {
            when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                24 -> {
                }

                else -> {
                    jj_la1[26] = jj_gen
                    break@label_5
                }
            }
            jj_consume_token(24)
            when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                SiteswapParserConstants.SPC -> {
                    jj_consume_token(SiteswapParserConstants.SPC)
                }

                else -> {
                    jj_la1[27] = jj_gen
                }
            }
            c = PassingThrows()
            if (c.beats != b.beats) {
                run { if (true) throw ParseException("Inconsistent number of beats between jugglers") }
            }
            b.addChild(c)
            current_juggler++
        }
        jj_consume_token(25)
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            SiteswapParserConstants.SPC -> {
                jj_consume_token(SiteswapParserConstants.SPC)
            }

            else -> {
                jj_la1[28] = jj_gen
            }
        }
        b.jugglers = current_juggler - 1
        if (jugglers == -1) jugglers = b.jugglers
        else if (b.jugglers != jugglers) {
            run { if (true) throw ParseException("Inconsistent number of jugglers") }
        }
        b.seq_beatnum = current_beat
        current_beat += b.beats
        run { if ("" != null) return b }
        throw Error("Missing return statement in function")
    }

    @Suppress("ControlFlowWithEmptyBody")
    @Throws(ParseException::class)
    fun PassingThrows(): SiteswapTreeItem {
        val b: SiteswapTreeItem
        var c: SiteswapTreeItem
        b = SiteswapTreeItem(SiteswapTreeItem.TYPE_PASSING_THROWS)
        current_beat_sub = 0
        label_6@ while (true) {
            when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                SiteswapParserConstants.NUM, SiteswapParserConstants.LET, 14, 16, 17 -> {
                    c = PassingMultiThrow()
                    current_beat_sub++
                    b.addChild(c)
                }

                9 -> {
                    c = PassingPairedThrow()
                    current_beat_sub += 2
                    when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                        12 -> {
                            jj_consume_token(12)
                            current_beat_sub--
                        }

                        else -> {
                            jj_la1[29] = jj_gen
                        }
                    }
                    when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                        SiteswapParserConstants.SPC -> {
                            jj_consume_token(SiteswapParserConstants.SPC)
                        }

                        else -> {
                            jj_la1[30] = jj_gen
                        }
                    }
                    b.addChild(c)
                }

                21, 22 -> {
                    c = PassingHandSpecifier()
                    when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                        SiteswapParserConstants.SPC -> {
                            jj_consume_token(SiteswapParserConstants.SPC)
                        }

                        else -> {
                            jj_la1[31] = jj_gen
                        }
                    }
                    b.addChild(c)
                }

                else -> {
                    jj_la1[32] = jj_gen
                    jj_consume_token(-1)
                    throw ParseException()
                }
            }
            if (jj_2_3(2147483647)) {
            } else {
                break@label_6
            }
        }
        b.source_juggler = current_juggler
        b.beats = current_beat_sub
        b.seq_beatnum = current_beat
        run { if ("" != null) return b }
        throw Error("Missing return statement in function")
    }

    @Throws(ParseException::class)
    fun PassingPairedThrow(): SiteswapTreeItem {
        val b: SiteswapTreeItem
        var c: SiteswapTreeItem
        b = SiteswapTreeItem(SiteswapTreeItem.TYPE_PASSING_PAIRED_THROW)
        jj_consume_token(9)
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            SiteswapParserConstants.SPC -> {
                jj_consume_token(SiteswapParserConstants.SPC)
            }

            else -> {
                jj_la1[33] = jj_gen
            }
        }
        c = PassingMultiThrow()
        b.addChild(c)
        jj_consume_token(13)
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            SiteswapParserConstants.SPC -> {
                jj_consume_token(SiteswapParserConstants.SPC)
            }

            else -> {
                jj_la1[34] = jj_gen
            }
        }
        c = PassingMultiThrow()
        b.addChild(c)
        jj_consume_token(11)
        b.source_juggler = current_juggler
        b.seq_beatnum = current_beat + current_beat_sub
        run { if ("" != null) return b }
        throw Error("Missing return statement in function")
    }

    @Throws(ParseException::class)
    fun PassingMultiThrow(): SiteswapTreeItem {
        val b: SiteswapTreeItem
        var c: SiteswapTreeItem
        b = SiteswapTreeItem(SiteswapTreeItem.TYPE_PASSING_MULTI_THROW)
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            SiteswapParserConstants.NUM, SiteswapParserConstants.LET, 16, 17 -> {
                c = PassingSingleThrow()
                b.addChild(c)
                when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                    SiteswapParserConstants.SPC -> {
                        jj_consume_token(SiteswapParserConstants.SPC)
                    }

                    else -> {
                        jj_la1[35] = jj_gen
                    }
                }
            }

            14 -> {
                jj_consume_token(14)
                when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                    SiteswapParserConstants.SPC -> {
                        jj_consume_token(SiteswapParserConstants.SPC)
                    }

                    else -> {
                        jj_la1[36] = jj_gen
                    }
                }
                label_7@ while (true) {
                    c = PassingSingleThrow()
                    b.addChild(c)
                    when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                        SiteswapParserConstants.SPC -> {
                            jj_consume_token(SiteswapParserConstants.SPC)
                        }

                        else -> {
                            jj_la1[37] = jj_gen
                        }
                    }
                    when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                        SiteswapParserConstants.NUM, SiteswapParserConstants.LET, 16, 17 -> {
                        }

                        else -> {
                            jj_la1[38] = jj_gen
                            break@label_7
                        }
                    }
                }
                jj_consume_token(15)
                when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                    SiteswapParserConstants.SPC -> {
                        jj_consume_token(SiteswapParserConstants.SPC)
                    }

                    else -> {
                        jj_la1[39] = jj_gen
                    }
                }
            }

            else -> {
                jj_la1[40] = jj_gen
                jj_consume_token(-1)
                throw ParseException()
            }
        }
        b.source_juggler = current_juggler
        b.seq_beatnum = current_beat + current_beat_sub
        run { if ("" != null) return b }
        throw Error("Missing return statement in function")
    }

    @Throws(ParseException::class)
    fun PassingSingleThrow(): SiteswapTreeItem {
        val b: SiteswapTreeItem
        var c: SiteswapTreeItem
        val t: Token
        var dest: Int
        val d: Int
        val mod: String?
        b = SiteswapTreeItem(SiteswapTreeItem.TYPE_PASSING_SINGLE_THROW)
        dest = current_juggler
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            SiteswapParserConstants.NUM -> {
                t = jj_consume_token(SiteswapParserConstants.NUM)
                b.value = (t.image?.toCharArray())?.get(0)?.digitToIntOrNull(36) ?: -1
            }

            SiteswapParserConstants.LET -> {
                t = jj_consume_token(SiteswapParserConstants.LET)
                b.value = (t.image?.toCharArray())?.get(0)?.digitToIntOrNull(36) ?: -1
            }

            16 -> {
                jj_consume_token(16)
                b.value = 25
            }

            17 -> {
                jj_consume_token(17)
                b.value = 33
            }

            else -> {
                jj_la1[41] = jj_gen
                jj_consume_token(-1)
                throw ParseException()
            }
        }
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            17 -> {
                jj_consume_token(17)
                b.x = true
            }

            else -> {
                jj_la1[42] = jj_gen
            }
        }
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            16 -> {
                jj_consume_token(16)
                dest = current_juggler + 1
                when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                    SiteswapParserConstants.NUM -> {
                        d = Number()
                        dest = d
                    }

                    else -> {
                        jj_la1[43] = jj_gen
                    }
                }
            }

            else -> {
                jj_la1[44] = jj_gen
            }
        }
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            SiteswapParserConstants.MOD -> {
                mod = Modifier()
                b.mod = mod
            }

            else -> {
                jj_la1[45] = jj_gen
            }
        }
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            20 -> {
                jj_consume_token(20)
            }

            else -> {
                jj_la1[46] = jj_gen
            }
        }
        b.source_juggler = current_juggler
        b.dest_juggler = dest
        b.seq_beatnum = current_beat + current_beat_sub
        run { if ("" != null) return b }
        throw Error("Missing return statement in function")
    }

    @Throws(ParseException::class)
    fun PassingHandSpecifier(): SiteswapTreeItem {
        val b: SiteswapTreeItem
        b = SiteswapTreeItem(SiteswapTreeItem.TYPE_HAND_SPEC)
        when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
            21 -> {
                jj_consume_token(21)
                b.spec_left = false
            }

            22 -> {
                jj_consume_token(22)
                b.spec_left = true
            }

            else -> {
                jj_la1[47] = jj_gen
                jj_consume_token(-1)
                throw ParseException()
            }
        }
        b.source_juggler = current_juggler
        b.seq_beatnum = current_beat + current_beat_sub
        run { if ("" != null) return b }
        throw Error("Missing return statement in function")
    }

    @Throws(ParseException::class)
    fun Number(): Int {
        var n: Token
        var s: String? = ""
        label_8@ while (true) {
            n = jj_consume_token(SiteswapParserConstants.NUM)
            s += n.image
            when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                SiteswapParserConstants.NUM -> {
                }

                else -> {
                    jj_la1[48] = jj_gen
                    break@label_8
                }
            }
        }
        var `val` = -1
        try {
            `val` = s.toInt()
        } catch (mfe: NumberFormatException) {
        }
        run { if ("" != null) return `val` }
        throw Error("Missing return statement in function")
    }

    @Throws(ParseException::class)
    fun Wildcard(): Int {
        var beats = 0
        label_9@ while (true) {
            jj_consume_token(26)
            beats++
            when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                26 -> {
                }

                else -> {
                    jj_la1[49] = jj_gen
                    break@label_9
                }
            }
        }
        run { if ("" != null) return beats }
        throw Error("Missing return statement in function")
    }

    @Throws(ParseException::class)
    fun Modifier(): String {
        var t: Token
        var mod = ""
        t = jj_consume_token(SiteswapParserConstants.MOD)
        mod += t.image
        label_10@ while (true) {
            when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                SiteswapParserConstants.MOD, 21, 22 -> {
                }

                else -> {
                    jj_la1[50] = jj_gen
                    break@label_10
                }
            }
            when (if (jj_ntk == -1) jj_ntk_f() else jj_ntk) {
                SiteswapParserConstants.MOD -> {
                    t = jj_consume_token(SiteswapParserConstants.MOD)
                    mod += t.image
                }

                22 -> {
                    jj_consume_token(22)
                    mod += "L"
                }

                21 -> {
                    jj_consume_token(21)
                    mod += "R"
                }

                else -> {
                    jj_la1[51] = jj_gen
                    jj_consume_token(-1)
                    throw ParseException()
                }
            }
        }
        run { if ("" != null) return mod }
        throw Error("Missing return statement in function")
    }

    private fun jj_2_1(xla: Int): Boolean {
        jj_la = xla
        jj_scanpos = token
        jj_lastpos = jj_scanpos
        try {
            return (!jj_3_1())
        } catch (ls: LookaheadSuccess) {
            return true
        } finally {
            jj_save(0, xla)
        }
    }

    private fun jj_2_2(xla: Int): Boolean {
        jj_la = xla
        jj_scanpos = token
        jj_lastpos = jj_scanpos
        try {
            return (!jj_3_2())
        } catch (ls: LookaheadSuccess) {
            return true
        } finally {
            jj_save(1, xla)
        }
    }

    private fun jj_2_3(xla: Int): Boolean {
        jj_la = xla
        jj_scanpos = token
        jj_lastpos = jj_scanpos
        try {
            return (!jj_3_3())
        } catch (ls: LookaheadSuccess) {
            return true
        } finally {
            jj_save(2, xla)
        }
    }

    private fun jj_3R_PassingThrows_352_25_82(): Boolean {
        if (jj_3R_PassingHandSpecifier_448_9_25()) return true
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        return false
    }

    private fun jj_3R_PassingPairedThrow_368_9_24(): Boolean {
        if (jj_scan_token(9)) return true
        var xsp: Token
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        if (jj_3R_PassingMultiThrow_384_9_23()) return true
        if (jj_scan_token(13)) return true
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        if (jj_3R_PassingMultiThrow_384_9_23()) return true
        if (jj_scan_token(11)) return true
        return false
    }

    private fun jj_3R_null_139_46_13(): Boolean {
        if (jj_3R_SoloPairedThrow_175_9_21()) return true
        return false
    }

    private fun jj_3R_SoloPairedThrow_175_9_21(): Boolean {
        if (jj_scan_token(9)) return true
        var xsp: Token
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        if (jj_3R_SoloMultiThrow_191_9_20()) return true
        if (jj_scan_token(13)) return true
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        if (jj_3R_SoloMultiThrow_191_9_20()) return true
        if (jj_scan_token(11)) return true
        return false
    }

    private fun jj_3R_PassingThrows_346_26_83(): Boolean {
        if (jj_scan_token(12)) return true
        return false
    }

    private fun jj_3R_SoloSequence_155_25_70(): Boolean {
        if (jj_3R_SoloHandSpecifier_252_9_22()) return true
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        return false
    }

    private fun jj_3R_PassingThrows_344_25_81(): Boolean {
        if (jj_3R_PassingPairedThrow_368_9_24()) return true
        var xsp: Token
        xsp = jj_scanpos!!
        if (jj_3R_PassingThrows_346_26_83()) jj_scanpos = xsp
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        return false
    }

    private fun jj_3R_SoloSequence_149_26_73(): Boolean {
        if (jj_scan_token(12)) return true
        return false
    }

    private fun jj_3R_PassingThrows_338_25_80(): Boolean {
        if (jj_3R_PassingMultiThrow_384_9_23()) return true
        return false
    }

    private fun jj_3R_SoloSequence_147_25_69(): Boolean {
        if (jj_3R_SoloPairedThrow_175_9_21()) return true
        var xsp: Token
        xsp = jj_scanpos!!
        if (jj_3R_SoloSequence_149_26_73()) jj_scanpos = xsp
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        return false
    }

    private fun jj_3R_null_336_27_15(): Boolean {
        if (jj_3R_PassingMultiThrow_384_9_23()) return true
        return false
    }

    private fun jj_3_3(): Boolean {
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_3R_null_336_27_15()) {
            jj_scanpos = xsp
            if (jj_3R_null_336_49_16()) {
                jj_scanpos = xsp
                if (jj_3R_null_336_72_17()) return true
            }
        }
        return false
    }

    private fun jj_3R_null_139_27_12(): Boolean {
        if (jj_3R_SoloMultiThrow_191_9_20()) return true
        return false
    }

    private fun jj_3_2(): Boolean {
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_3R_null_139_27_12()) {
            jj_scanpos = xsp
            if (jj_3R_null_139_46_13()) {
                jj_scanpos = xsp
                if (jj_3R_null_139_66_14()) return true
            }
        }
        return false
    }

    private fun jj_3R_SoloSequence_141_25_68(): Boolean {
        if (jj_3R_SoloMultiThrow_191_9_20()) return true
        return false
    }

    private fun jj_3R_PassingThrows_336_17_79(): Boolean {
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_3R_PassingThrows_338_25_80()) {
            jj_scanpos = xsp
            if (jj_3R_PassingThrows_344_25_81()) {
                jj_scanpos = xsp
                if (jj_3R_PassingThrows_352_25_82()) return true
            }
        }
        return false
    }

    private fun jj_3R_SoloSequence_139_17_63(): Boolean {
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_3R_SoloSequence_141_25_68()) {
            jj_scanpos = xsp
            if (jj_3R_SoloSequence_147_25_69()) {
                jj_scanpos = xsp
                if (jj_3R_SoloSequence_155_25_70()) return true
            }
        }
        return false
    }

    private fun jj_3R_PassingThrows_331_9_74(): Boolean {
        var xsp: Token
        if (jj_3R_PassingThrows_336_17_79()) return true
        while (true) {
            xsp = jj_scanpos!!
            if (jj_3R_PassingThrows_336_17_79()) {
                jj_scanpos = xsp
                break
            }
        }
        return false
    }

    private fun jj_3R_SoloSequence_133_9_46(): Boolean {
        var xsp: Token
        if (jj_3R_SoloSequence_139_17_63()) return true
        while (true) {
            xsp = jj_scanpos!!
            if (jj_3R_SoloSequence_139_17_63()) {
                jj_scanpos = xsp
                break
            }
        }
        return false
    }

    private fun jj_3R_Modifier_504_17_78(): Boolean {
        if (jj_scan_token(21)) return true
        return false
    }

    private fun jj_3R_Modifier_501_17_77(): Boolean {
        if (jj_scan_token(22)) return true
        return false
    }

    private fun jj_3R_GroupedPattern_123_10_19(): Boolean {
        if (jj_scan_token(10)) return true
        if (jj_3R_Number_467_9_28()) return true
        return false
    }

    private fun jj_3R_Modifier_498_17_72(): Boolean {
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_3R_Modifier_498_17_76()) {
            jj_scanpos = xsp
            if (jj_3R_Modifier_501_17_77()) {
                jj_scanpos = xsp
                if (jj_3R_Modifier_504_17_78()) return true
            }
        }
        return false
    }

    private fun jj_3R_Modifier_498_17_76(): Boolean {
        if (jj_scan_token(SiteswapParserConstants.MOD)) return true
        return false
    }

    private fun jj_3R_PassingGroup_304_17_75(): Boolean {
        if (jj_scan_token(24)) return true
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        if (jj_3R_PassingThrows_331_9_74()) return true
        return false
    }

    private fun jj_3R_GroupedPattern_117_9_11(): Boolean {
        if (jj_scan_token(9)) return true
        if (jj_3R_Pattern_86_9_18()) return true
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_3R_GroupedPattern_123_10_19()) jj_scanpos = xsp
        if (jj_scan_token(11)) return true
        return false
    }

    private fun jj_3_1(): Boolean {
        if (jj_3R_GroupedPattern_117_9_11()) return true
        return false
    }

    private fun jj_3R_Modifier_495_9_66(): Boolean {
        if (jj_scan_token(SiteswapParserConstants.MOD)) return true
        var xsp: Token
        while (true) {
            xsp = jj_scanpos!!
            if (jj_3R_Modifier_498_17_72()) {
                jj_scanpos = xsp
                break
            }
        }
        return false
    }

    private fun jj_3R_Pattern_96_25_40(): Boolean {
        if (jj_3R_Wildcard_485_9_48()) return true
        return false
    }

    private fun jj_3R_Pattern_94_25_39(): Boolean {
        if (jj_3R_PassingSequence_272_9_47()) return true
        return false
    }

    private fun jj_3R_Pattern_92_25_38(): Boolean {
        if (jj_3R_SoloSequence_133_9_46()) return true
        return false
    }

    private fun jj_3R_Pattern_89_25_37(): Boolean {
        if (jj_3R_GroupedPattern_117_9_11()) return true
        return false
    }

    private fun jj_3R_Pattern_104_10_27(): Boolean {
        if (jj_scan_token(8)) return true
        return false
    }

    private fun jj_3R_Wildcard_485_11_65(): Boolean {
        if (jj_scan_token(26)) return true
        return false
    }

    private fun jj_3R_Wildcard_485_9_48(): Boolean {
        var xsp: Token
        if (jj_3R_Wildcard_485_11_65()) return true
        while (true) {
            xsp = jj_scanpos!!
            if (jj_3R_Wildcard_485_11_65()) {
                jj_scanpos = xsp
                break
            }
        }
        return false
    }

    private fun jj_3R_PassingGroup_293_9_71(): Boolean {
        if (jj_scan_token(23)) return true
        var xsp: Token
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        if (jj_3R_PassingThrows_331_9_74()) return true
        while (true) {
            xsp = jj_scanpos!!
            if (jj_3R_PassingGroup_304_17_75()) {
                jj_scanpos = xsp
                break
            }
        }
        if (jj_scan_token(25)) return true
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        return false
    }

    private fun jj_3R_Pattern_88_17_26(): Boolean {
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_3R_Pattern_89_25_37()) {
            jj_scanpos = xsp
            if (jj_3R_Pattern_92_25_38()) {
                jj_scanpos = xsp
                if (jj_3R_Pattern_94_25_39()) {
                    jj_scanpos = xsp
                    if (jj_3R_Pattern_96_25_40()) return true
                }
            }
        }
        return false
    }

    private fun jj_3R_PassingSequence_277_17_64(): Boolean {
        if (jj_3R_PassingGroup_293_9_71()) return true
        return false
    }

    private fun jj_3R_Number_468_17_41(): Boolean {
        if (jj_scan_token(SiteswapParserConstants.NUM)) return true
        return false
    }

    private fun jj_3R_Pattern_86_9_18(): Boolean {
        var xsp: Token
        if (jj_3R_Pattern_88_17_26()) return true
        while (true) {
            xsp = jj_scanpos!!
            if (jj_3R_Pattern_88_17_26()) {
                jj_scanpos = xsp
                break
            }
        }
        xsp = jj_scanpos!!
        if (jj_3R_Pattern_104_10_27()) jj_scanpos = xsp
        return false
    }

    private fun jj_3R_Number_467_9_28(): Boolean {
        var xsp: Token
        if (jj_3R_Number_468_17_41()) return true
        while (true) {
            xsp = jj_scanpos!!
            if (jj_3R_Number_468_17_41()) {
                jj_scanpos = xsp
                break
            }
        }
        return false
    }

    private fun jj_3R_PassingSequence_272_9_47(): Boolean {
        var xsp: Token
        if (jj_3R_PassingSequence_277_17_64()) return true
        while (true) {
            xsp = jj_scanpos!!
            if (jj_3R_PassingSequence_277_17_64()) {
                jj_scanpos = xsp
                break
            }
        }
        return false
    }

    private fun jj_3R_PassingHandSpecifier_453_17_36(): Boolean {
        if (jj_scan_token(22)) return true
        return false
    }

    private fun jj_3R_PassingHandSpecifier_450_17_35(): Boolean {
        if (jj_scan_token(21)) return true
        return false
    }

    private fun jj_3R_SoloHandSpecifier_257_17_32(): Boolean {
        if (jj_scan_token(22)) return true
        return false
    }

    private fun jj_3R_SoloHandSpecifier_254_17_31(): Boolean {
        if (jj_scan_token(21)) return true
        return false
    }

    private fun jj_3R_PassingHandSpecifier_448_9_25(): Boolean {
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_3R_PassingHandSpecifier_450_17_35()) {
            jj_scanpos = xsp
            if (jj_3R_PassingHandSpecifier_453_17_36()) return true
        }
        return false
    }

    private fun jj_3R_PassingSingleThrow_433_21_62(): Boolean {
        if (jj_3R_Modifier_495_9_66()) return true
        return false
    }

    private fun jj_3R_SoloHandSpecifier_252_9_22(): Boolean {
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_3R_SoloHandSpecifier_254_17_31()) {
            jj_scanpos = xsp
            if (jj_3R_SoloHandSpecifier_257_17_32()) return true
        }
        return false
    }

    private fun jj_3R_PassingSingleThrow_429_20_61(): Boolean {
        if (jj_scan_token(16)) return true
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_3R_PassingSingleThrow_431_18_67()) jj_scanpos = xsp
        return false
    }

    private fun jj_3R_PassingSingleThrow_431_18_67(): Boolean {
        if (jj_3R_Number_467_9_28()) return true
        return false
    }

    private fun jj_3R_SoloSingleThrow_237_20_55(): Boolean {
        if (jj_3R_Modifier_495_9_66()) return true
        return false
    }

    private fun jj_3R_PassingSingleThrow_423_25_59(): Boolean {
        if (jj_scan_token(17)) return true
        return false
    }

    private fun jj_3R_PassingSingleThrow_420_25_58(): Boolean {
        if (jj_scan_token(16)) return true
        return false
    }

    private fun jj_3R_PassingSingleThrow_427_18_60(): Boolean {
        if (jj_scan_token(17)) return true
        return false
    }

    private fun jj_3R_SoloSingleThrow_235_18_54(): Boolean {
        if (jj_scan_token(17)) return true
        return false
    }

    private fun jj_3R_SoloSingleThrow_227_25_52(): Boolean {
        if (jj_scan_token(17)) return true
        return false
    }

    private fun jj_3R_PassingSingleThrow_417_25_57(): Boolean {
        if (jj_scan_token(SiteswapParserConstants.LET)) return true
        return false
    }

    private fun jj_3R_SoloSingleThrow_224_25_51(): Boolean {
        if (jj_scan_token(16)) return true
        return false
    }

    private fun jj_3R_PassingSingleThrow_414_25_56(): Boolean {
        if (jj_scan_token(SiteswapParserConstants.NUM)) return true
        return false
    }

    private fun jj_3R_SoloSingleThrow_221_25_50(): Boolean {
        if (jj_scan_token(SiteswapParserConstants.LET)) return true
        return false
    }

    private fun jj_3R_SoloSingleThrow_218_25_49(): Boolean {
        if (jj_scan_token(SiteswapParserConstants.NUM)) return true
        return false
    }

    private fun jj_3R_SoloSingleThrow_230_13_53(): Boolean {
        if (jj_scan_token(18)) return true
        var xsp: Token
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        if (jj_3R_Number_467_9_28()) return true
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        if (jj_scan_token(19)) return true
        return false
    }

    private fun jj_3R_PassingSingleThrow_408_9_44(): Boolean {
        var xsp: Token
        xsp = jj_scanpos!!
        if (jj_3R_PassingSingleThrow_414_25_56()) {
            jj_scanpos = xsp
            if (jj_3R_PassingSingleThrow_417_25_57()) {
                jj_scanpos = xsp
                if (jj_3R_PassingSingleThrow_420_25_58()) {
                    jj_scanpos = xsp
                    if (jj_3R_PassingSingleThrow_423_25_59()) return true
                }
            }
        }
        xsp = jj_scanpos!!
        if (jj_3R_PassingSingleThrow_427_18_60()) jj_scanpos = xsp
        xsp = jj_scanpos!!
        if (jj_3R_PassingSingleThrow_429_20_61()) jj_scanpos = xsp
        xsp = jj_scanpos!!
        if (jj_3R_PassingSingleThrow_433_21_62()) jj_scanpos = xsp
        xsp = jj_scanpos!!
        if (jj_scan_token(20)) jj_scanpos = xsp
        return false
    }

    private fun jj_3R_PassingMultiThrow_392_25_45(): Boolean {
        if (jj_3R_PassingSingleThrow_408_9_44()) return true
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        return false
    }

    private fun jj_3R_SoloSingleThrow_215_9_42(): Boolean {
        var xsp: Token
        xsp = jj_scanpos!!
        if (jj_3R_SoloSingleThrow_218_25_49()) {
            jj_scanpos = xsp
            if (jj_3R_SoloSingleThrow_221_25_50()) {
                jj_scanpos = xsp
                if (jj_3R_SoloSingleThrow_224_25_51()) {
                    jj_scanpos = xsp
                    if (jj_3R_SoloSingleThrow_227_25_52()) {
                        jj_scanpos = xsp
                        if (jj_3R_SoloSingleThrow_230_13_53()) return true
                    }
                }
            }
        }
        xsp = jj_scanpos!!
        if (jj_3R_SoloSingleThrow_235_18_54()) jj_scanpos = xsp
        xsp = jj_scanpos!!
        if (jj_3R_SoloSingleThrow_237_20_55()) jj_scanpos = xsp
        xsp = jj_scanpos!!
        if (jj_scan_token(20)) jj_scanpos = xsp
        return false
    }

    private fun jj_3R_SoloMultiThrow_199_25_43(): Boolean {
        if (jj_3R_SoloSingleThrow_215_9_42()) return true
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        return false
    }

    private fun jj_3R_null_336_72_17(): Boolean {
        if (jj_3R_PassingHandSpecifier_448_9_25()) return true
        return false
    }

    private fun jj_3R_PassingMultiThrow_390_17_34(): Boolean {
        if (jj_scan_token(14)) return true
        var xsp: Token
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        if (jj_3R_PassingMultiThrow_392_25_45()) return true
        while (true) {
            xsp = jj_scanpos!!
            if (jj_3R_PassingMultiThrow_392_25_45()) {
                jj_scanpos = xsp
                break
            }
        }
        if (jj_scan_token(15)) return true
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        return false
    }

    private fun jj_3R_SoloMultiThrow_197_17_30(): Boolean {
        if (jj_scan_token(14)) return true
        var xsp: Token
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        if (jj_3R_SoloMultiThrow_199_25_43()) return true
        while (true) {
            xsp = jj_scanpos!!
            if (jj_3R_SoloMultiThrow_199_25_43()) {
                jj_scanpos = xsp
                break
            }
        }
        if (jj_scan_token(15)) return true
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        return false
    }

    private fun jj_3R_PassingMultiThrow_386_17_33(): Boolean {
        if (jj_3R_PassingSingleThrow_408_9_44()) return true
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        return false
    }

    private fun jj_3R_SoloMultiThrow_193_17_29(): Boolean {
        if (jj_3R_SoloSingleThrow_215_9_42()) return true
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_scan_token(7)) jj_scanpos = xsp
        return false
    }

    private fun jj_3R_null_139_66_14(): Boolean {
        if (jj_3R_SoloHandSpecifier_252_9_22()) return true
        return false
    }

    private fun jj_3R_PassingMultiThrow_384_9_23(): Boolean {
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_3R_PassingMultiThrow_386_17_33()) {
            jj_scanpos = xsp
            if (jj_3R_PassingMultiThrow_390_17_34()) return true
        }
        return false
    }

    private fun jj_3R_SoloMultiThrow_191_9_20(): Boolean {
        val xsp: Token
        xsp = jj_scanpos!!
        if (jj_3R_SoloMultiThrow_193_17_29()) {
            jj_scanpos = xsp
            if (jj_3R_SoloMultiThrow_197_17_30()) return true
        }
        return false
    }

    private fun jj_3R_null_336_49_16(): Boolean {
        if (jj_3R_PassingPairedThrow_368_9_24()) return true
        return false
    }

    /** Generated Token Manager.  */
    var token_source: SiteswapParserTokenManager?
    lateinit var jj_input_stream: SimpleCharStream

    /** Current token.  */
    var token: Token?

    /** Next token.  */
    var jj_nt: Token? = null
    private var jj_ntk: Int
    private var jj_scanpos: Token? = null
    private var jj_lastpos: Token? = null
    private var jj_la = 0
    private var jj_gen: Int
    private val jj_la1 = IntArray(52)
    private var jj_2_rtns: Array<JJCalls> = Array(3) { JJCalls() }
    private var jj_rescan = false
    private var jj_gc = 0

    /** Constructor with a String. */
    constructor(input: String) {
        jj_input_stream = SimpleCharStream(input, 1, 1)
        token_source = SiteswapParserTokenManager(jj_input_stream)
        token = Token()
        jj_ntk = -1
        jj_gen = 0
        for (i in 0..51) jj_la1[i] = -1
        for (i in jj_2_rtns.indices) jj_2_rtns[i] = JJCalls()
    }

    /** Reinitialise. */
    fun ReInit(input: String) {
        jj_input_stream.ReInit(input, 1, 1)
        token_source!!.ReInit(jj_input_stream)
        token = Token()
        jj_ntk = -1
        jj_gen = 0
        for (i in 0..51) jj_la1[i] = -1
        for (i in jj_2_rtns.indices) jj_2_rtns[i] = JJCalls()
    }

    /** Constructor with generated Token Manager.  */
    constructor(tm: SiteswapParserTokenManager?) {
        token_source = tm
        token = Token()
        jj_ntk = -1
        jj_gen = 0
        for (i in 0..51) jj_la1[i] = -1
        for (i in jj_2_rtns.indices) jj_2_rtns[i] = JJCalls()
    }

    /** Reinitialise.  */
    fun ReInit(tm: SiteswapParserTokenManager?) {
        token_source = tm
        token = Token()
        jj_ntk = -1
        jj_gen = 0
        for (i in 0..51) jj_la1[i] = -1
        for (i in jj_2_rtns.indices) jj_2_rtns[i] = JJCalls()
    }

    @Throws(ParseException::class)
    private fun jj_consume_token(kind: Int): Token {
        val oldToken: Token?
        if ((token.also { oldToken = it })?.next != null) token = token?.next
        else {
            token?.next = token_source!!.nextToken
            token = token?.next
        }
        jj_ntk = -1
        if (token?.kind == kind) {
            jj_gen++
            if (++jj_gc > 100) {
                jj_gc = 0
                for (i in jj_2_rtns.indices) {
                    var c: JJCalls? = jj_2_rtns[i]
                    while (c != null) {
                        if (c.gen < jj_gen) c.first = null
                        c = c.next
                    }
                }
            }
            return token!!
        }
        token = oldToken
        jj_kind = kind
        throw generateParseException()
    }

    private class LookaheadSuccess : Error() {
        override fun fillInStackTrace(): Throwable {
            return this
        }
    }

    private fun jj_scan_token(kind: Int): Boolean {
        if (jj_scanpos === jj_lastpos) {
            jj_la--
            if (jj_scanpos!!.next == null) {
                jj_scanpos!!.next = token_source!!.nextToken
                jj_scanpos = jj_scanpos!!.next
                jj_lastpos = jj_scanpos
            } else {
                jj_scanpos = jj_scanpos!!.next
                jj_lastpos = jj_scanpos
            }
        } else {
            jj_scanpos = jj_scanpos!!.next
        }
        if (jj_rescan) {
            var i = 0
            var tok = token
            while (tok != null && tok !== jj_scanpos) {
                i++
                tok = tok.next
            }
            if (tok != null) jj_add_error_token(kind, i)
        }
        if (jj_scanpos!!.kind != kind) return true
        if (jj_la == 0 && jj_scanpos === jj_lastpos) throw jj_ls
        return false
    }


    val nextToken: Token
        /** Get the next Token.  */
        get() {
            if (token?.next != null) token = token!!.next
            else {
                token?.next = token_source!!.nextToken
                token = token?.next
            }
            jj_ntk = -1
            jj_gen++
            return token!!
        }

    /** Get the specific Token.  */
    fun getToken(index: Int): Token {
        var t = token
        for (i in 0..<index) {
            if (t?.next != null) t = t.next
            else {
                t?.next = token_source!!.nextToken
                t = t?.next
            }
        }
        return t!!
    }

    private fun jj_ntk_f(): Int {
        if ((token?.next.also { jj_nt = it }) == null) {
            return ((token_source!!.nextToken
                .also { token?.next = it })?.kind.also {
                    if (it != null) {
                        jj_ntk = it
                    }
                }!!)
        }
        else return (jj_nt!!.kind.also { jj_ntk = it })
    }

    private val jj_expentries: MutableList<IntArray> = ArrayList<IntArray>()
    private var jj_expentry: IntArray? = null
    private var jj_kind = -1
    private val jj_lasttokens = IntArray(100)
    private var jj_endpos = 0

    private fun jj_add_error_token(kind: Int, pos: Int) {
        if (pos >= 100) {
            return
        }

        if (pos == jj_endpos + 1) {
            jj_lasttokens[jj_endpos++] = kind
        } else if (jj_endpos != 0) {
            jj_expentry = IntArray(jj_endpos)

            for (i in 0..<jj_endpos) {
                jj_expentry!![i] = jj_lasttokens[i]
            }

            for (oldentry in jj_expentries) {
                if (oldentry.size == jj_expentry!!.size) {
                    var isMatched = true

                    for (i in jj_expentry!!.indices) {
                        if (oldentry[i] != jj_expentry!![i]) {
                            isMatched = false
                            break
                        }
                    }
                    if (isMatched) {
                        jj_expentries.add(jj_expentry!!)
                        break
                    }
                }
            }

            if (pos != 0) {
                jj_lasttokens[(pos.also { jj_endpos = it }) - 1] = kind
            }
        }
    }

    /** Generate ParseException.  */
    @Suppress("UNCHECKED_CAST")
    fun generateParseException(): ParseException {
        jj_expentries.clear()
        val la1tokens = BooleanArray(27)
        if (jj_kind >= 0) {
            la1tokens[jj_kind] = true
            jj_kind = -1
        }
        for (i in 0..51) {
            if (jj_la1[i] == jj_gen) {
                for (j in 0..31) {
                    if ((jj_la1_0[i] and (1 shl j)) != 0) {
                        la1tokens[j] = true
                    }
                }
            }
        }
        for (i in 0..26) {
            if (la1tokens[i]) {
                jj_expentry = IntArray(1)
                jj_expentry!![0] = i
                jj_expentries.add(jj_expentry!!)
            }
        }
        jj_endpos = 0
        jj_rescan_token()
        jj_add_error_token(0, 0)
        val exptokseq = arrayOfNulls<IntArray>(jj_expentries.size)
        for (i in jj_expentries.indices) {
            exptokseq[i] = jj_expentries.get(i)
        }
        return ParseException(token!!, exptokseq,
            SiteswapParserConstants.tokenImage as Array<String?>
        )
    }

    private var trace_enabled = false

    /** Trace enabled.  */
    fun trace_enabled(): Boolean {
        return trace_enabled
    }

    /** Enable tracing.  */
    fun enable_tracing() {
    }

    /** Disable tracing.  */
    fun disable_tracing() {
    }

    private fun jj_rescan_token() {
        jj_rescan = true
        for (i in 0..2) {
            try {
                var p: JJCalls? = jj_2_rtns[i]

                do {
                    p?.gen?.let {
                        if (it > jj_gen) {
                            jj_la = p.arg
                            jj_scanpos = p.first
                            jj_lastpos = jj_scanpos
                            when (i) {
                                0 -> jj_3_1()
                                1 -> jj_3_2()
                                2 -> jj_3_3()
                            }
                        }
                    }
                    p = p?.next
                } while (p != null)
            } catch (ls: LookaheadSuccess) {
            }
        }
        jj_rescan = false
    }

    private fun jj_save(index: Int, xla: Int) {
        var p: JJCalls? = jj_2_rtns[index]
        p?.gen?.let {
            while (it > jj_gen) {
                if (p?.next == null) {
                    p?.next = JJCalls()
                    p = p?.next
                    break
                }
                p = p.next
            }
        }

        p?.gen = jj_gen + xla - jj_la
        p?.first = token
        p?.arg = xla
    }

    internal class JJCalls {
        var gen: Int = 0
        var first: Token? = null
        var arg: Int = 0
        var next: JJCalls? = null
    }

    companion object {
        private var jugglers = 0
        private var current_juggler = 0
        private var current_beat = 0
        private var current_beat_sub = 0

        @Throws(ParseException::class)
        fun parsePattern(pat: String): SiteswapTreeItem {
            val parser = SiteswapParser(pat)
            jugglers = -1
            return (parser.MakeTree())
        }

        // For test purposes
        @Throws(ParseException::class)
        @JvmStatic
        fun main(args: Array<String>) {
            val `in` = args[0]
            println("parsing pattern: " + `in`)
            println(parsePattern(`in`))
        }

        private var jj_la1_0: IntArray = intArrayOf(
            0x80,
            0x4e74230,
            0x4e74230,
            0x100,
            0x400,
            0x1000,
            0x80,
            0x80,
            0x674230,
            0x80,
            0x80,
            0x80,
            0x80,
            0x80,
            0x70030,
            0x80,
            0x74030,
            0x80,
            0x80,
            0x70030,
            0x20000,
            0x40,
            0x100000,
            0x600000,
            0x800000,
            0x80,
            0x1000000,
            0x80,
            0x80,
            0x1000,
            0x80,
            0x80,
            0x634230,
            0x80,
            0x80,
            0x80,
            0x80,
            0x80,
            0x30030,
            0x80,
            0x34030,
            0x30030,
            0x20000,
            0x10,
            0x10000,
            0x40,
            0x100000,
            0x600000,
            0x10,
            0x4000000,
            0x600040,
            0x600040,
        )


        private val jj_ls = LookaheadSuccess()
    }
}
