/* Generated By:JavaCC: Do not edit this line. SiteswapParserConstants.java */
package jugglinglab.notation.ssparser


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface SiteswapParserConstants {
    companion object {
        /** End of File.  */
        const val EOF: Int = 0

        /** RegularExpression Id.  */
        const val NUM: Int = 4

        /** RegularExpression Id.  */
        const val LET: Int = 5

        /** RegularExpression Id.  */
        const val MOD: Int = 6

        /** RegularExpression Id.  */
        const val SPC: Int = 7

        /** Lexical state.  */
        const val DEFAULT: Int = 0

        /** Literal token values.  */
        val tokenImage: Array<String> = arrayOf(
            "<EOF>",
            "\"\\t\"",
            "\"\\n\"",
            "\"\\r\"",
            "<NUM>",
            "<LET>",
            "<MOD>",
            "<SPC>",
            "\"*\"",
            "\"(\"",
            "\"^\"",
            "\")\"",
            "\"!\"",
            "\",\"",
            "\"[\"",
            "\"]\"",
            "\"p\"",
            "\"x\"",
            "\"{\"",
            "\"}\"",
            "\"/\"",
            "\"R\"",
            "\"L\"",
            "\"<\"",
            "\"|\"",
            "\">\"",
            "\"?\"",
        )
    }
}
